name: Modbus MQTT Bridge
description: Home Assistant Addon to bridge modbus devices to MQTT
version: 1.2.6
slug: modbus_mqtt_bridge
init: false
ingress: true
uart: true
panel_icon: mdi:network
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
map:
  - config:ro
